### ISSUE TITLE
Triggering of abuse rate limits when updating a lot of tasks

### ISSUE THREAD

**Issue by slaykovsky** [freeipa/freeipa-pr-ci#192]
Now, prci may trigger abuse rate limit https://developer.github.com/v3/ on GitHub when it needs to update a lot of statuses simultaneously. Especially, when it started to poll and change state after deploy.

@akokshar has some good ideas how to eliminate this kind of nasty thing.

Also, to decrease API usage more, after executing a task, prci need to get all the new state at once - to break a
```python
        for pull_request in pull_requests:
            for task in process_pull_request(world, pull_request, repo_url):
```
loop and to get into the 

```python
while not exit_handler.done:
```
loop.

**Comment by slaykovsky** [comment]
I've made temporary workaround in https://github.com/freeipa/freeipa-pr-ci/commit/e87a80b8a241b8125619d02f05f70c9fc93ef5e1

**Comment by netoarmando** [comment]
This problem could be addressed by having a central controller in PR-CI, like the one proposed by  https://github.com/freeipa/freeipa-pr-ci/issues/159#issuecomment-366732603.

Closing this for now, since the workaround has been working and this seems something we should fix by changing the architecture of the project.
