### ISSUE TITLE
github: adjust PR priority (older first)

### ISSUE THREAD

**Issue by tomaskrizek** [freeipa/freeipa-pr-ci#75]
When PR task queue is constructed, older PR should be handled sooner than newly opened PRs. This should prevent situation when old PR waits a long time for tests, because many new PR are being opened (e.g. backport PR after pushing).

**Comment by davidkupka** [comment]
Currently, the priority of the task is 3-tuple:
- prioritized tuple is present on PR
- priority of the task in task file
- number of processed or started tasks on PR

This ensures that the prioritized PRs are tested ASAP and also tends to finishing testing of PR rather than starting testing new one.

You can add age of the PR as  4th member of the tuple but I don't think you'll see dramatic change. The fact that PR CI prefers tasks from semi-processed PRs should in most cases have very similar effect.

**Comment by tomaskrizek** [comment]
Actually, I think this feature is not desirable. When a new template / test is added, the new tests are executed on all PRs. This would prioritize older PRs, which should have a lower priority in this case. I'd just stick with the default sorting we have now.
