### ISSUE TITLE
Only run failed jobs on re-run

### ISSUE THREAD

**Issue by stlaz** [freeipa/freeipa-pr-ci#81]
It does not make sense to build and run all jobs if only one job out of x failed. Run only one job on a re-run request, all jobs are run on a rebase anyway.

**Comment by davidkupka** [comment]
@stlaz you're right re-running successful test without change in code doesn't make sense in most situations. But what about running tests? I think that there isn't universal answer and it depends on situation.
I think that it would be ideal to trigger re-run per task. Unfortunately GitHub doesn't provide any means of modifying commit statuses from WebUI. On the other hand there's API and it would be really easy to create CLI tool that would allow that.
My idea is something like this:
```
# prci-test-control list <PR-NUM>
<context> <state> <description> <url>
<context> <state> <description> <url>
... 
# prci-test-control rerun <PR-NUM> {<context> | --state {success | failure | error | pending} | --all}
N tests will be re-run.
```
Then the 're-run' label would only trigger ru-run for tests in state error and failure and everything else would be handled with prci-test-control tool.

Would this work for you? I can contribute both prci-test-control and the change in 're-run' behaviour.

**Comment by tomaskrizek** [comment]
I think the re-run label can be used both for triggering a test run from external contributors and re-executing all failed jobs. The re-run label could do the following:

- if there are jobs that do not have a corresponding commit status, create it (for test runs)
- if there are jobs that have a corresponding commit status and the status is failed/error, create a new unassigned status (for re-running failed tests)

Complete test re-runs can be triggered by a rebase.

@davidkupka Such a tool would be great, since we would have the option not to spam re-run labels in PRs. Contributions are welcome :)

**Comment by davidkupka** [comment]
@tomaskrizek that's exactly what I wanted to say. But as always you can express my thoughts better that I.
