### ISSUE TITLE
Use git tag when releasing a new box version

### ISSUE THREAD

**Issue by felipevolpone** [freeipa/freeipa-pr-ci#84]
I think it could be a good idea create a new git tag every time we release a new vagrant box version, this way it would be easy to know what features/code/etc each box version has.

**Comment by tomaskrizek** [comment]
Do we really need to know how the box was created? A minor box update should be executed frequently and it should primarily update the packages. There's also nothing that prevents you from creating a box from a commit that's not in git (I used to do this when switching between f25/f26).

Initially, I manually added the commit number to each version of released box, but I found little use for it, so I stopped doing that. Since we want to keep only most recent boxes available (last working version and a new version), I don't think they should differ in functionality too much.

The maintained boxes should be re-generated periodically every few weeks, so we can more or less assume the code in master is pretty much what's in the most recent box.

**Comment by stlaz** [comment]
I don't really understand what a box update has to do with a version of a PRCI project. Should we ever decide to separate PRCI from IdM completely as a general purpose multi-host PR CI, the decision to create a tag whenever a new testing box is released would only hurt this project.

**Comment by tomaskrizek** [comment]
@stlaz When the box is created/updated, it uses a [playbook](https://github.com/freeipa/freeipa-pr-ci/blob/master/ansible/create_template_box.yml) from the repo. The action it performs can change, so you may end up with two boxes with slightly different config.

**Comment by stlaz** [comment]
@tomaskrizek Huh, I see. I should have added that I don't know the PRCI internals. Not sure if it's possible but it might be worth thinking about making the core of the project independent of box changes, possibly having the playbooks in `contrib/` and allow specifying user-defined template boxes creation.

Just my 20 halíř.

**Comment by felipevolpone** [comment]
Let me describe my reasons here: last week tkrizek was on PTO and standa ask me to add a new dependency on the box. I checked the freeipa's PRs and saw that Tomas had a PR updating the box version. In this case the PR was just a backport to 4.6 branch, however, if he had a PR to master, I would not be able to be sure that the code on master was the "content" of the new box version. And this possibility is the reason for this issue.

Anyway, if you think that this would not bring any value to the project, ok.

my 20 [centavos](https://en.wikipedia.org/wiki/Brazilian_real#Second_series_.281998.E2.80.93present.29)

**Comment by tomaskrizek** [comment]
You can get a list of installed packages in the template by examining the [runner.log.gz](https://fedorapeople.org/groups/freeipa/prci/jobs/74312c56-a28d-11e7-bb30-fa163e62a181/runner.log.gz), step `machine/provision : get all packages`. This after ansible provisioning, so it also contains `freeipa-*` and `python*-ipatests`, which isn't present in the base template -- but if you just want to check whether a package is present or not, it can be used.

Production templates should always be generated from the master branch, so you could check what the code looked like at the time the [template](https://app.vagrantup.com/freeipa/boxes/ci-master-f26/versions/0.1.3) was created.
